name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build the Docker image
        run: |
          docker build -t my-flask-app .

      - name: Tag the Docker image
        run: |
          docker tag my-flask-app:latest 050515008040.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecs-flask:${{ github.run_number }}

      - name: Push the Docker image
        run: |
          docker push 050515008040.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecs-flask:${{ github.run_number }}
